### ISSUE TITLE
Fails to save any SI file

### ISSUE THREAD

**Issue by yoshi-wiimote** [isledecomp/SIEdit#15]
Whenever I try to save an SI file, it gives me an error that says "Failed to write SI file: 1". I tried with JUKEBOXW.SI (not JUKEBOX.SI) and it didn't work, it didn't even work for NOCD.SI.

**Comment by itsmattkc** [comment]
You don't have permissions to write to the directory you're trying to write to. Save somewhere else, or change the folder's permissions, or run SIEdit as administrator.
